package com.example.jpademo.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.transaction.Transactional;

@Entity
@Data
@NoArgsConstructor
public class User {

    // id can't generated by EntityManager persist method.
    // There are four different GenerationType: AUTO, IDENTITY, SEQUENCE, TABLE
    // Hibernate creates a new table named hibernate_sequence for the next id value.
    @Id
    @GeneratedValue
    private int id;
    private String name;
    private String email;

    public User(String name, String email) {
        this.name = name;
        this.email = email;
    }

    public User(Integer id, String name, String email) {
        this.id = id;
        this.name=name;
        this.email=email;
    }
}
